openapi: "3.0.0"
info:
  version: 1.0.0
  title: API
  license:
    name: MIT
paths:
  /clients:
    get:
      summary: List all clients
      operationId: listClients
      responses:
        '200':
          description: An array of clients
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clients"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a client
      operationId: createClients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /clients/{clientId}:
    get:
      summary: Info for a specific client
      operationId: showClientById
      parameters:
        - name: clientId
          in: path
          required: true
          description: The id of the client to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /clients/import:
    post:
      summary: Import Clients CSV data
      operationId: importClients
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '202':
          description: Accepted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /appointments:
    get:
      summary: List all appointments
      operationId: listAppointments
      responses:
        '200':
          description: An array of appointments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointments"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an appointment
      operationId: createAppointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Appointment"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /appointments/{appointmentId}:
    get:
      summary: Info for a specific appointment
      operationId: showAppointmentById
      parameters:
        - name: appointmentId
          in: path
          required: true
          description: The id of the appointment to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /appointments/import:
    post:
      summary: Import Appointments CSV data
      operationId: importAppointments
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '202':
          description: Accepted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /purchases:
    get:
      summary: List all purchases
      operationId: listPurchases
      responses:
        '200':
          description: An array of purchases
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Purchases"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a purchase
      operationId: createPurchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Purchase"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Purchase"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /purchases/{purchaseId}:
    get:
      summary: Info for a specific purchase
      operationId: showPurchaseById
      parameters:
        - name: purchaseId
          in: path
          required: true
          description: The id of the purchase to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Purchase"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /purchases/import:
    post:
      summary: Import Purchases CSV data
      operationId: importPurchases
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '202':
          description: Accepted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Client:
      type: object
      required:
        - firstName
        - lastName
        - email
        - phone
        - gender
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
        gender:
          $ref: "#/components/schemas/Gender"
        banned:
          type: boolean
    Clients:
      type: array
      items:
        $ref: "#/components/schemas/Client"
    Gender:
      enum:
        - Male
        - Female
    Appointment:
      type: object
      required:
        - clientId
        - startTime
        - endTime
      properties:
        id:
          type: string
          format: uuid
        clientId:
          type: string
          format: uuid
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    Appointments:
      type: array
      items:
        $ref: "#/components/schemas/Appointment"
    Purchase:
      type: object
      required:
        - clientId
        - startTime
        - endTime
      properties:
        id:
          type: string
          format: uuid
        appointmentId:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
          format: double
        loyaltyPoints:
          type: integer
    Purchases:
      type: array
      items:
        $ref: "#/components/schemas/Purchase"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
